// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use diesel::{deserialize::Queryable, prelude::Insertable, Selectable};
use serde::{Deserialize, Serialize};

use crate::schema::{posts, users};

#[derive(Queryable, Debug, Serialize, Deserialize, Insertable, Selectable)]
#[diesel(table_name = posts)]
pub struct Post {
    pub id: i32,
    pub user_id: i32,
    pub title: String,
    pub body: String,
    pub published: bool,
}

#[derive(Queryable, Debug, Serialize, Deserialize, Insertable, Selectable)]
#[diesel(table_name = users)]
pub struct User {
    pub id: i32,
    pub nickname: String,
    pub password: String,
}

